### ISSUE TITLE
<<yeartoyear>> gives "2021 - 2021"

### ISSUE THREAD

**Issue by aschepler** [davidquinn/psi-header#12]
When the `<<yeartoyear>>` system function is used without argument parentheses in a template invoked for a new file or file created within the current year, it fails to collapse the identical year limits into the short form. The resulting text is "2021 - 2021".

Workaround: If used with parentheses but no explicit arguments, as `<<yeartoyear()>>`, the function does behave as advertised, giving the text "2021".

[psioniq File Header v1.15.1, VS Code 1.56.2, on Ubuntu x64 20.04.2]

**Comment by davidquinn** [comment]
This is a simple bug in the `getVariables()` helper function.  I will provide a fix for it later today.

Regards
David

**Comment by davidquinn** [comment]
Fix included in v1.15.2
