### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kumarwork007** [davidquinn/psi-header#20]
- Issue Type: `Performance`
- Extension Name: `psi-header`
- Extension Version: `1.15.2`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\pc\AppData\Local\Temp\psioniq.psi-header-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by davidquinn** [comment]
So, any clues? What were you doing when this happened? Were you saving a big file? Were you adding a heading? Were you saving changes to a file that already had a header? What other extensions are you using? Did you read the warning message in what you posted and if so where is the file that it told you to attach?

**Comment by davidquinn** [comment]
I am closing this because I can't do anything with the information provided. Feel free to re-open and provide some more detail.
