### ISSUE TITLE
How to ignore files with their file extension or file name? 

### ISSUE THREAD

**Issue by EnkiduGilgamesh** [davidquinn/psi-header#27]
I modifiered a configuration file with ".spec" extension in VSC. Every time I save it, the comments inserts into the file automatically . I have tried to several configuration with "exclude" and "excludeGlob" argument to ignore this kind of extension, but they all seemed not working. I might set a wrong parameters to the above argument. 
Could you give me a specific example to help me do as my expect? Thank you!

**Comment by davidquinn** [comment]
I am not sure what you have tried, but the following should work (insert just the excludeGlob line into your existing configuration):

```
 "psi-header.changes-tracking": {
        "excludeGlob": ["./**/*/*.spec"],
    },
```

or probably even the following if you have not installed a language extension for .spec files:

```
 "psi-header.changes-tracking": {
        "exclude": ["plaintext"],
    },
```

HTH
David

**Comment by EnkiduGilgamesh** [comment]
Thank you for your reply! The configuration:

```
 "psi-header.changes-tracking": {
        "excludeGlob": ["./**/*/*.spec"],
    },
```

is what I have tried. Maybe I forgot to save the settings.json, so the configuration didn't work that time. 

Now, I configure the extension as I except. Thank you one more time for your hard work to build this nice work for us!

**Comment by EnkiduGilgamesh** [comment]
This is how I configured:

```
"psi-header.changes-tracking": {
		"isActive": true,
		"modAuthor": "Modified By:",
		"modDate": "Last Modified:",
		"modDateFormat": "dd/MM/yyyy hh:nn:ss",
		"include": [],
		"includeGlob": [],
		"exclude": ["markdown", "json", "jsonc", "shellscript", "ignore"],
		"excludeGlob": ["./**/*/*.spec"],
		"autoHeader": "autoSave",
		"enforceHeader": true,
		"replace": [
			"File:",
			"Project:"
		],
		"updateLicenseVariables": true
    },
```

But the `excludeGlob` seems not work correctly. I modifier it like above, but every time I save a .spec file, the header is inserted automatically still.

**Comment by davidquinn** [comment]
I just tested it with the glob and it didn't work - not sure why. However if you use the other approach and add "plaintext" to `exclude` then it should work. In the meantime I will investigate the glob exclude further.

Regards
David

**Comment by EnkiduGilgamesh** [comment]
I am using `plaintext` for now. This is a nice extension, and I am looking forward to your fixing this issue.

**Comment by davidquinn** [comment]
I have just done some more investigation and it seems that the following slightly modified version does work:
```
"psi-header.changes-tracking": {
        "excludeGlob": ["**/*/*.spec"],
    },
```
Sorry for the bad steer in the previous suggestion.

**Comment by EnkiduGilgamesh** [comment]
Thanks, the modified version does work perfectly which is what I want. 

In [market](https://marketplace.visualstudio.com/items?itemName=psioniq.psi-header#configuration) , the example below: 

```
"psi-header.changes-tracking": {
        "excludeGlob": ["./**/*/ignoreme.*"],
    },
```

is given to users. 

I just tested that this version didn't work, too, whereas the `"**/*/ignoreme.*"` version does work. I think this example probably make big misdirection to users who are reading it. 

Maybe you can modify the documentation in market when you are available.

**Comment by davidquinn** [comment]
I have uploaded a fix - turns out the original issue with globs was caused when Microsoft removed the concept of "root folder" from workspaces. You can now use globs that start with either a `**` or `.` so the original example in the documentation now works again.
