### ISSUE TITLE
How set timezone

### ISSUE THREAD

**Issue by wcb33** [davidquinn/psi-header#28]
the ```<<date>>``` is returned UTC time, but OS timezone not UTC, how config the timezone?

**Comment by davidquinn** [comment]
The `<<date>>` variable returns the current date using the standard Javascript Date.toDateString() so it should not be UTC.

You can format the date as you wish though using the `<<dateformat()>>` system function (refer to the documentation). This function uses the momentJS formatting

The following configuration within the template:
```
    "Date: <<date>>",
    "Time: <<time>>",
    "FormatDate: <<dateformat(YY-MM-DD hh:mm:ss)>>",
    "FormatDateUTC: <<dateformat(YY-MM-DD hh:mm:ssZZ)>>",
```

gives the following results:
```
 * Date: Sat Dec 04 2021
 * Time: 7:21:23 AM
 * FormatDate: 2021-12-04 07:21:23
 * FormatDateUTC: 2021-12-04 07:21:23+00:00
```

Regards
David

**Comment by Chuanbin-Wang** [comment]
My bad, I actually used this
```
Last Modified: <<dateformat('YYYY-MM-DD hh:mm:ss')>>
```
the result:
```
 * Last Modified: 2021-12-09 08:28:57
```
The OS time is: 20:28:57.

And this:
```
Last Modified: <<dateformat('YYYY-MM-DD hh:mm:ss')>>
```
the result just add +8000 in the end. 

How get the OS time with custom format? 
OS time:20:28:57 -> result 
```
 * Last Modified: 2021-12-09 20:28:57
```

**Comment by davidquinn** [comment]
The date format parameter can be any momentJS date string. So, you can do any of the following, depending on your requirements:
```javascript
    "am/pm: <<dateformat(YY-MM-DD hh:mm:ss a)>>" // ==> 2021-12-04 08:28:57 am
    "AM/PM: <<dateformat(YY-MM-DD hh:mm:ss A)>>" // ==> 2021-12-04 08:28:57 AM
    "24hour: <<dateformat(YY-MM-DD HH:mm:ss)>>" // ==> 2021-12-04 20:28:57
```

Refer to the [momentJS documentation](https://momentjs.com/docs/#/displaying/) for more information on the available formats.

Regards
David

**Comment by Chuanbin-Wang** [comment]
From the documentation only the Z/ZZ flag.  it will add +08:00/+0800 in the end.
But this is not good for reading for non-standard time zones。
I found some solution:
Call tz function before format in helper.ts line 757 and 768.
```
moment().tz( ${tz from config} ).format(args);
```

Thinks

**Comment by davidquinn** [comment]
OK. I am planning on doing some updates at the end of the year so I will take a look at this as part of those updates.

**Comment by Maelep** [comment]
```
"<<filecreated('YYYYMMDDThhmmss')>>Z",
"<<dateformat('YYYYMMDDThhmmss')>>Z",

// filecreated: 20220308T011814Z
// dateformat: 20220308T023859Z
```

`filecreated` returns UTC but `dateformat` returns my computer time.
Would you be able to make it consistency by always returning UTC or be able to add a timezone in the config file?

**Comment by davidquinn** [comment]
On re-reading these, I can see that the OPs problem was actually resolved in the original solution I proposed. The key was to use `HH` instead of `hh` to generate the output in 24 hour format. No need for anything related to UTC - it just works as per the [MomentJS](https://momentjs.com) documentation.

D
