### ISSUE TITLE
Updating the file date does not work

### ISSUE THREAD

**Issue by Esquimen** [davidquinn/psi-header#29]
Good evening, it seems to me that I have configured my settings correctly but when I save my file again with modifications it does not update the date. Is there a bug?

Here are my settings:
````
        "psi-header.config": {
            "forceToTop": true,
            "blankLinesAfter": 0,
            "creationDateZero": "now",
        },
        "psi-header.changes-tracking": {
            "isActive": true,
            "modAuthor": "@lastModifiedBy: ",
            "modDate": "@lastModifiedTime: ",
        },
        "psi-header.lang-config": [
            {
                "language": "shellscript",
                "begin": "",
                "prefix": "# ",
                "end": "",
            }
        ],
        "psi-header.templates": [
            {
                "language": "*",
                "template": [
                    "@author: <<author>> <<<authoremail>>>",
                    "@date:   <<filecreated('DD-MM-YYYY HH:mm:ss')>>",
                    "@lastModifiedBy:   <<author>> <<<authoremail>>>",
                    "@lastModifiedTime: <<dateformat('YYYY-MM-DD HH:mm:ss')>>",
                ],
                
            }
        ]
````

**Comment by davidquinn** [comment]
Your configuration as posted looks and works fine here - the last modified time is updating when I save the file after having made changes.

I assume you are only expecting the value associated with the line `@lastModifiedTime` to change?
Are you sure that you made changes to the file before saving? (it only updates the header when VSC reports the file as being dirty)
Are you sure you do not have conflicting settings?  (i.e. do you possibly have both User and Workspace settings - VSC merges them together)
Have you made changes to the template after creating the file? (e.g. renamed the line that starts `@lastModifiedTime`)

Regards
David

**Comment by Esquimen** [comment]
Thank you very much for taking the time to answer me.

I turned off my pc yesterday and this morning it works so I guess you have to either close VSCode completely after installing your extensions or you have to restart the pc completely because I spent some time looking and looking and it doesn't work.
After reboot it works!

Thanks
Mathieu

**Comment by davidquinn** [comment]
That is very strange. I haven't had to restart BSC before to add/change configuration but they do sometimes change how they interact with extensions. Are you sure you had saved your settings changes (sorry, have to ask)?

Glad it all works now

Regards
David

**Comment by Esquimen** [comment]
Yes I'm sure I had made changes and saved.
What is strange is that when I modify the template in the settings.json it works fine but not if I made changes in the file. I didn't have the date to change

**Comment by gjgjh** [comment]
I think I had the same issue here, and resarting VSC does help :-)

**Comment by davidquinn** [comment]
Possibly a change in the way VSC refreshes after changes to the settings. I will investigate soon.

D
