### ISSUE TITLE
Option to omit spaces from `yeartoyear` output

### ISSUE THREAD

**Issue by simon-abbott** [davidquinn/psi-header#32]
Currently the `yeartoyear` function outputs in the format `YYYY - YYYY`. I would prefer it if it were `YYYY-YYYY` (no spaces), but the format is hardcoded. Would it be possible to add some sort of option to control the output format?

**Comment by davidquinn** [comment]
Hi Simon,

I am in the middle of moving house (to a different "country") but I should be up and running again early next week. I'll take a look and let you know what I can do.

Regards
David

**Comment by Maelep** [comment]
Hello, is this feature available? If yes, how can I remove the spaces?

**Comment by davidquinn** [comment]
this has been released in v1.18.0
