### ISSUE TITLE
How to configure to ignore .env files?

### ISSUE THREAD

**Issue by rscafidi** [davidquinn/psi-header#37]
I'm having trouble figuring out how to utilize either "exclude" or "excludeGlob" to ignore .env files.  Any characters in a .env file cause issues for some of my applications to parse the .env file so I want to make sure .env files are ignored.  Currently, the global config gets applied to them on save.  Only way I was able to get around it is to set the global config to add no header, however I still want to use the global config for other files I have not made a configuration for yet.  Any help/example config for how to ignore .env file would be helpful.  Here's what I have so far in the psi-header.changes-tracking config:

`
"psi-header.changes-tracking": {

		"isActive": true,
		"modAuthor": "Modified By:",
		"modDate": "Last Modified:",
		"modDateFormat": "DD MMM YYYY",
		"include": [],
		"includeGlob": [],
		"exclude": [],
		"excludeGlob": ["./**/*/ignoreme.*", "*.env"],
		"autoHeader": "autoSave",
		"enforceHeader": true,
		"replace": [],
		"updateLicenseVariables": false
	},
`

**Comment by davidquinn** [comment]
Try the following for your excludeGlob setting: 

``
"excludeGlob": ["**/*/*.env"],
``

The example in the readme is wrong - I need to fix it.

Regards
David

**Comment by rscafidi** [comment]
Hi David, thanks for the suggestion, but `"excludeGlob": ["**/*/*.env"]` it doesn't appear to affect the .env file.  I will mess with the config a bit more to see if I can find out what i'm missing and post back if I figure it out.
