### ISSUE TITLE
Option for not updating header after resolving GIT merge conflict

### ISSUE THREAD

**Issue by junajted** [davidquinn/psi-header#39]
Hi, after I merge or cherry-pick, I sometimes have conflicts and after resolving them, "modified by" headers also get updated, but I do not want that. 

Is it possible to add an option for disabling headers update when branch is in such "merging" states (for example when I'm resolving cherry pick conflicts, branch name is "<branch-name>|CHERRY-PICKING")

Or does something like that already exists?

Thanks!

**Comment by davidquinn** [comment]
Hi,

I am sorry but there is nothing currently in the extension that would allow that. Unfortunately VSC only tells us that the file is being saved, but not why - so I have no idea if the save is as a result of a merge.

Happy for someone to propose a pull request to the extension if they can figure a way to implement this, but I don't think it is achievable.

Regards
David

**Comment by junajted** [comment]
Hi

after file is saved, it can be checked if git repository is in merge state by firing shell command https://stackoverflow.com/questions/30733415/how-to-determine-if-git-merge-is-in-process.

**Comment by davidquinn** [comment]
Hi,

That will not work as the header is updated __during__ the save, so by the time we get here the "modified by" is already updated. 

A mute point (as during save is the only opportunity that VSC exposes for the extension to track changes) but if it worked after the file was saved it would put the extension into an endless loop as each save would then cause a re-triggering of the extension.

The solution in your link only tells you __if__ a merge is happening not whether the file being saved is part of that merge. I kind of agree with one of the commenters on the selected answer too that this method is a rather smelly hack.

Also, firing this off as a shell command is likely to cause VSC to disable the extension. VSC only allows a brief time (a matter of milliseconds) for an extension to perform an action. If it takes longer it is disabled, and shell execution can take a while to complete.

Also, as I mentioned before, this relies on git being installed.

I think the only way to do this would be to tap into VSCs support for version control systems but I am not sure if that will give you what you want. I am happy for you to propose a solution via a pull request, but it will have to (a) be cross-platform; (b) cope with all version control systems supported by VSC; (c) able to be disabled via configuration; and (d) not adversely affect performance of the extension.

Regards
David

**Comment by junajted** [comment]
Hi
Thanks for taking the time to explain. Unfortunately, I don't have experiences building VSC extensions so I won't tackle the problem. Workaround for me is then using other tool for handling merge conflicts.
Cheers,
J
