### ISSUE TITLE
I miss the relative path within the project as variable

### ISSUE THREAD

**Issue by ChristianToepfer** [davidquinn/psi-header#41]
I need the `filerelativepath` without filename. 
`relativepath` - The relative path within the project

With this new variable, the user can write `<<relativepath>><<filename>>` insteat of `<<filerelativepath>>`
It makes `filerelativepath` redundant. 

Christian

**Comment by davidquinn** [comment]
I will look to add an additional variable for relative path without filename over the next few days.

D

**Comment by ChristianToepfer** [comment]
Great, works fine!
Thanks Christian
