### ISSUE TITLE
Publish on openvsx?

### ISSUE THREAD

**Issue by jlk** [davidquinn/psi-header#46]
Hi there - I'm pondering switching over to [vscodium](https://vscodium.com/), which uses a separate extension repo from vscode. Would it be possible to publish to [open-vsx?](https://open-vsx.org/) Instructions are [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). 

Been using the plugin for a year or two, quite fond of it. Thanks for the work!

**Comment by xdevc512l** [comment]
Any news on this? I'm not a vscode extension developer but looks like its fairly easy to publish extensions according to the [docs](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by davidquinn** [comment]
Have not done so yet, but it is on my to do list to review what is required.

Hopefully over the next week or so.

Regards
D

**Comment by davidquinn** [comment]
I have taken a look and it looks doable, but there are some bureaucratic bits that I have to go through in order to safely publish. So my aim is to sort that out first then I can properly test that the extension works with it (it should).

**Comment by davidquinn** [comment]
I have published the extension now, but it currently shows as unverified. I am awaiting Open VSX to approve my request for ownership of the namespace.

I will post here again and close this issue once the ownership request has been approved.

**Comment by davidquinn** [comment]
Ownership has been approved, so I will close this issue now.
