### ISSUE TITLE
language with file extension not working

### ISSUE THREAD

**Issue by soulraven** [davidquinn/psi-header#47]
i have this config...
and is not working, when i try to instart the header it defaults back to the default header.
Somehow is ignoring the extensions.

>         {
> 			"language": ".fact.j2",
> 			"begin": "",
> 			"prefix": "# ",
> 			"end": "",
> 			"blankLinesAfter": 0,
> 			"beforeHeader": [
> 				"#!{{ ansible_python['executable'] }}",
> 				"# -*- coding:utf-8 -*-\n"
> 			],
>             "ignoreLines": [
>                 "#!"
>             ]
> 		},
>         {
> 			"language": ".conf.j2",
> 			"begin": "{#",
> 			"prefix": "# ",
> 			"end": "#}",
> 			"blankLinesAfter": 0,
> 			"beforeHeader": [],
>             "ignoreLines": [
>                 "{# "
>             ]
> 		},

>         {
>             "language": ".fact.j2",
>             "template": [
>                 "Copyright (C) <<yeartoyear(2021,now)>> <<author>> <constantin.zaharia@progeek.ro>",
>                 "Copyright (C) <<yeartoyear(2021,now)>> <<company>> <<<companyWebsite>>>",
>                 "SPDX-License-Identifier: <<spdxid>>"
>             ]
>         },
>         {
>             "language": ".conf.j2",
>             "template": [
>                 "Copyright (C) <<yeartoyear(2021,now)>> <<author>> <constantin.zaharia@progeek.ro>",
>                 "Copyright (C) <<yeartoyear(2021,now)>> <<company>> <<<companyWebsite>>>",
>                 "SPDX-License-Identifier: <<spdxid>>"
>             ]
>         },

**Comment by davidquinn** [comment]
Hi,

This is not an issue with the extension. The reason it doesn't work is that the OS is returning the file extension of the file as __"the *last* dot and the text after it"__. So in your examples, the extension is trying to find a matching language definition where `language == ".j2"`.

Regards
D

**Comment by soulraven** [comment]
hi,
ok, so in the case where is present with double extensions, like in ansible templates? what to do? is there any work around?

**Comment by davidquinn** [comment]
The best way is to use the language id in the configuration (rather than file extension). The list of supported language IDs for your machine can be found by accessing the "Select Language Mode" list from the VSC status bar (the IDs are the part in brackets against each entry). For example, by default, VSC treats .config.j2 files as PlainText (languageId = plaintext). PlainText is the default if it doesn't recognise the extension.

Even though VSC doesn't natively recognise your files, you can add this capability by installing an extension that adds language support to VSC. So you may already have something installed that solves it for you. I think the files you are using are Jinja and there are extensions that provide language support for that. There is also an extension from RedHat that provides ansible support. 

HTH
Regards
D

**Comment by soulraven** [comment]
yes, the files format is jinja, but is jinja that's exports file in different formats, py, config. Jinja is used only as template for that basic file.
That's the point of the double extension, to know what is the output format file.
The idea is to identify each file format with specific extension and apply the header specific to that file format.

**Comment by davidquinn** [comment]
So do you have any of the Jinja language extensions installed? If so, what do you see as the file type in the status bar when you load each of your files. 

Take a look at the extension called "Better Jinga" - it adds a large number of language extensions which cover what you need (click on the Feature Contributions to see the extensive list of file extensions that it adds language support for). Also, the ansible extension adds support for .ansible.yml and .ansible.yaml.

**Comment by soulraven** [comment]
Yes, is working like this, is an interesting workaround, not the best because will add overhead, but is working.
Possibile in the future will consider to support multiple extensions formats.

**Comment by davidquinn** [comment]
No plans to do what you are asking at the moment for a couple of reasons: 

(a) it isn't a workaround - it is how VSC is designed to work - it includes built in support for some common languages and expects that you will install extensions to provide language support for the languages that are not built in. This is the most efficient way to work (also see note later); and 

(b) this extension already has 2 mechanisms for determining the type of file: VSC Language ID and OS-reported file extension. Adding a third option to determine this would add more overhead than using the existing language support which would affect all users unnecessarily.

I had contact with MS a while back about a proposal to expose more information about the language in the VSC Extensions API now. That functionality will allow me to remove the need for a large part of the language configuration in this extension going forward - so installing language support is definitely the correct way to go.

Regards
D
