### ISSUE TITLE
Excluding .json from generating header comment

### ISSUE THREAD

**Issue by st-clair-clarke** [davidquinn/psi-header#52]
Hi,
How can I exclude *.json file from generating a header comment? I see a psi-header.changes-tracking.exclude property but no similar ones in the config examples.

**Comment by davidquinn** [comment]
It is the `changes-tracking.exclude` setting. From your other issue I can see you are using `enforceHeading` in changes tracking - this is what is causing headers to be created in your json files. This is discussed in [this section](https://github.com/davidquinn/psi-header#enforce-header) of the documentation.

Regards
D

**Comment by st-clair-clarke** [comment]
Thank you very much. Everything works now. You have an amazing plugin.

**Comment by davidquinn** [comment]
Excellent and thanks.

Regards
D
