### ISSUE TITLE
Include/Exclude Globs have no way to reference the working folder

### ISSUE THREAD

**Issue by cxbrettbaker** [davidquinn/psi-header#53]
When using a glob to include/exclude a file, this will work:
```
 "**/.gitkeep"
```
But this will not work:
```
 "./.gitkeep"
```

Could also be the reason why you ran into this problem back in this issue:
https://github.com/davidquinn/psi-header/issues/27#issuecomment-966060701

**Comment by davidquinn** [comment]
Thanks - I am just taking a look at it. The extension uses minimatch for the glob pattern matching so I am going to start there.

D

**Comment by davidquinn** [comment]
v1.21.1 has now been uploaded to the marketplace to fix this.
