### ISSUE TITLE
Including W for Week of Year

### ISSUE THREAD

**Issue by meyverick** [davidquinn/psi-header#58]
Is it possible to add W when using Week Year in `modDateFormat`? I would like to make `"modDateFormat": "YYYY-WWW-E"` where the first "W" is a plain letter, not something to parse to obtain `2023-W25-7`.

**Comment by davidquinn** [comment]
The date strings are created via MomentJS, so you can use any formatting supported in [their docs](http://momentjs.com/docs/#/displaying/format/). 

Regards
D

**Comment by davidquinn** [comment]
Looking at their docs, you can do what you want by wrapping the W in square brackets.

D
