### ISSUE TITLE
Using the same 'begin' and 'end' results in failure to insert change-log

### ISSUE THREAD

**Issue by HZomor** [davidquinn/psi-header#60]
Hello,

When "changeLogNaturalOrder" is true, the extension checks for the first occurrence of the 'end' pattern. 
Maybe if you can first compare it to the 'begin' and use the second occurrence if they match it would fix the problem.

Thanks again! It's a really nice extension.

**Comment by davidquinn** [comment]
I think you might be right - if it is in natural order and the header is _not_ in compact mode, then it should start of testing if it is "inComment".

I will update it asap.

D

**Comment by HZomor** [comment]
Thank You! :)

**Comment by davidquinn** [comment]
I have uploaded version 1.21.2 that fixes this issue to the marketplace. It should be available to install now.

Regards
D

**Comment by davidquinn** [comment]
And then...1.21.3 version removes debug comment that was being written to the console.

:{

**Comment by HZomor** [comment]
thanks a lot!
