### ISSUE TITLE
The <<yeartoyear(fc!P,now)>> won't update the copyright information

### ISSUE THREAD

**Issue by diverger** [davidquinn/psi-header#61]
I have a template like below:

      "psi-header.templates": [
        {
          "language": "*",
          "template": [
               "Last Modified: <<dateformat('dddd, YYYY/MM/DD H:mm:ss')>>",
              "",
              "Copyright (c) <<yeartoyear(fc!P,now)>> <<company>>",
              "---------------------------------------------------------",
              "HISTORY:"
          ],  
          "changeLogCaption": "HISTORY:",
          "replace": [ "Copyright" ]
        }
      ],
  
      "psi-header.changes-tracking": {      
      "isActive": true
      },

But after file changed and saved. The year to year information won't change to current year.

**Comment by davidquinn** [comment]
Hi,

The `replace` property belongs in the `psi-header.lang-config` section not in the `psi-header.templates` section.

HTH

D

**Comment by diverger** [comment]
Hi,

I see it in Option 2 Template Substitution, the 'replace' is indeed in 'templates' section.

Thanks.

**Comment by davidquinn** [comment]
The example in the documentation was not correct and I have pushed a change to the documentation. You can either put the replace in the `changes-tracking` section to have it used globally or in any `lang-config` entry to override for a specific language. But it does not go in the `templates` section.
