### ISSUE TITLE
Header reinsertion with shortcut zoom

### ISSUE THREAD

**Issue by HZomor** [davidquinn/psi-header#65]
Hello, 

I am having an issue where the header gets reinserted whenever I zoom in or out using shortcut. The extension also tries to insert headers into non-text windows with zooming (eg. settings, or extension pages).

I tried changing the shortcuts and still have the same behaviour. It doesn't happen when I do it through the command palette though.

Thank you for your support!

Best,
HZomor

**Comment by davidquinn** [comment]
I haven't been able to reproduce your problem. I suspect it is likely to be another extension that is using the shortcut keys to do something to the current document.

Can you check if any of your extensions are set up to use those keys? Or try disabling all other extensions and reactivate one by one until the problem reoccurs.

Regards
David

**Comment by HZomor** [comment]
Hello @davidquinn! sorry for the very late response. 

I finally figured out the root cause of the problem. It was indeed due to another extension, but it was more complex than just a clash. The [other extension](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office) opened markdown in a rich editor format. As a result, psioniq sees it as a document to add the header automatically to, yet it fails to add it. The solution was to exclude Markdown from the auto-headers.

Why this happened when zooming in or out, I honestly have no idea, but the shortcut is definitely not assigned to anything else. I am guessing, using the zoom shortcut specifically causes psioniq to recheck the currently active document or vscode to do an automatic save, which triggers psioniq. It seemed to happen when any unsupported document was open and the active document was a supported one, which resulted in adding a new header.

Hope this helps you for future development and thanks again for your efforts!

Regards
HZomor
