### ISSUE TITLE
The system function filecreated cannot obtain the time

### ISSUE THREAD

**Issue by wwwHui** [davidquinn/psi-header#74]
I use the Remote-SSh of vscode on win10 to edit the remote code on ubuntu. The system function filecreated cannot obtain the time, showing 1970-1-1.
examples :
<<filecreated('YYYY-MM-DD HH:mm:ss')>>
<<dateformat('YYYY-MM-DD HH:mm:ss')>>
results:
1970-01-01 08:00:00
2024-06-21 09:29:53

**Comment by davidquinn** [comment]
This is a known issue with certain versions of Linux and is addressed [here in the README](https://github.com/davidquinn/psi-header?tab=readme-ov-file#determining-file-creation-time-on-linux).

Regards
D

**Comment by wwwHui** [comment]
Sorry to bother you.

**Comment by davidquinn** [comment]
Not a problem.

D
