### ISSUE TITLE
ignoreLines not working

### ISSUE THREAD

**Issue by OverHealz** [davidquinn/psi-header#75]
I have a line that needs to be on top for another extension.

local BUILD = '

Here is my config, it is not ignoring this line:

 "psi-header.lang-config": [
        {
            "language": "lua",
            "begin": "--[[ BEGIN AUTOMATIC HEADER",
            "prefix": "*****    ",
            "suffix": "*****    ",
            "lineLength": 100,
            "end": "END AUTOMATIC HEADER --]]",
            "forceToTop": true,
            "blankLinesAfter": 2,
            "rootDirFileName": "README.md",
            "ignoreLines": [ "local BUILD = '" ],
        },

**Comment by davidquinn** [comment]
You need to use the `beforeHeader` option under Language Configuration for the pre-header stuff.

Regards
D
