### ISSUE TITLE
what a terriable plugin it is!

### ISSUE THREAD

**Issue by lifeyf** [davidquinn/psi-header#76]
the modified date do not update,cost my two hours to figure it out, FAILED!!
this plug is just for waste your time, just follow the instructions, seems jump into a river, VERY HARD TO USE!

**Comment by davidquinn** [comment]
The modified date does update. Maybe [this](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct) might help you work out how to get help when you need it.

Regards
D
