### ISSUE TITLE
Feature Request:  <<filename>> tag that excludes extension

### ISSUE THREAD

**Issue by OverHealz** [davidquinn/psi-header#77]
for instance if the filename is

     filename.lua

it would only use filename

This is useful for using the header to start defining classed after the general header information.

**Comment by davidquinn** [comment]
I will look to get this in over the next couple of days.

D

**Comment by OverHealz** [comment]
thank you

**Comment by OverHealz** [comment]
just a little bump...:)

**Comment by davidquinn** [comment]
Yep :). I haven't forgotten. 

D

**Comment by davidquinn** [comment]
So, I just fired up VSC to do this and realised that it is already available! Just use `<<filenamebase>>` instead of `<<filename>>`.

Regards
D

**Comment by OverHealz** [comment]
thank you
